name: $(Date:yyyyMMdd)$(Rev:.r)

trigger:
  batch: true
  branches:
    include:
      - main

pool:
  name: StagingLinux2

variables:
  dockerRepository: testing/cypress
  dockerfilePath: ./Dockerfile.build

steps:
  - checkout: self
    clean: true

  - task: Docker@2
    displayName: Login to DkCR1
    inputs:
      command: login
      containerRegistry: DkContainerRegistry1

  - task: Docker@2
    displayName: Build image with SAS_TOKEN
    inputs:
      command: build
      containerRegistry: DkContainerRegistry1
      Dockerfile: $(dockerfilePath)
      repository: $(dockerRepository)
      arguments: |
        --build-arg SAS_TOKEN=$(SAS_TOKEN)
      tags: |
        $(Build.BuildNumber)

  - task: Docker@2
    displayName: Push image
    inputs:
      command: push
      containerRegistry: DkContainerRegistry1
      repository: $(dockerRepository)
      tags: |
        $(Build.BuildNumber)

  - task: Docker@2
    displayName: Logout from DkCR1
    inputs:
      command: logout
      containerRegistry: DkContainerRegistry1
